version: "3.9"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app # Mounts your server directory into /app in the container
    environment:
      - FLASK_ENV=development
